### ISSUE TITLE
Asset flow scenarios

### ISSUE THREAD

**Issue by canhtrinh** [axelarnetwork/axelar-web-app#1]
---
name: Asset flows
about: Epic that governs task list of individual asset flows in the UI

---

## Rationale ##
The UI should be able to support asset transfers across blockchains. Initial use cases below.

## Owner ##
TBU

## Description ##
- [ ] BTC to/from an EVM chain (say, Ethereum),
- [ ] BTC to/from Axelar network,
- [ ] BTC to/from other cosmos chains (say, Terra for now) assets from cosmos chains (Terra) to/from other EVM chains

## Proof ##
