### ISSUE TITLE
UI datadog error handling and logging of all flows by TRACE_ID

### ISSUE THREAD

**Issue by canhtrinh** [axelarnetwork/axelar-web-app#27]
## Description
Programmatically improve error-handling and logging across ui and rest server layers. 
When code-level errors arise, the logging should clearly indicate what those errors are

- [ ]  log all "catch" conditions to datadog as errors
- [ ]  log all steps by TRACE_ID into datadog that can be debugged by user
- [ ] from the rest-server, all non-200 responses should indicate what specific errors are. 

## Todos

- [ ] Unit tests
- [ ] Manual tests
- [ ] Documentation
- [ ] Connect epics/issues
- [ ] Tag type of change

## Other Notes
