### ISSUE TITLE
incorporate UI comments from 11/26 ceremony

### ISSUE THREAD

**Issue by canhtrinh** [axelarnetwork/axelar-web-app#64]
## Description
- [x] Generating Source Chain Deposit Address -> Generating a Deposit Address
- [x] Return to submit transaction
- [ ] MS add retry in coming weeks for confirming deposit address
- [x] Copy to Clipboard seems like a button, not a tooltip
- [x] "most frequent flows"

## Todos

- [ ] Unit tests
- [x] Manual tests
- [ ] Documentation
- [ ] Connect epics/issues
- [ ] Tag type of change

## Other Notes
