### ISSUE TITLE
Handle failed deposit txs made in step 2 of the transaction status screen

### ISSUE THREAD

**Issue by canhtrinh** [axelarnetwork/axelar-web-app#98]
## Description
* Some have reported that when deposits are made in step 2, the UI either doesn't update correctly with proper messaging or gives a non-helpful response. 
* When a user makes a deposit either by IBC transfer or Metamask transfer to make the deposit in step 2, and if the transaction isn't successful, we should say why and also log it to datadog. 

Possible reasons for a failed deposit tx:
* IBC
     - [x]  account sequence mismatch - [@João Sousa] reported
     - [x]  insufficient funds issue - [@Jackson] reported
     - [x]  out of gas issues (known from before
     - [x]  outright rejecting a tx from Keplr
* EVM
     - [x]  insufficient funds issue - [@Jackson] reported
     - [x]  out of gas issues (known from before
     - [x]  outright rejecting a tx from Metamask
     
## Todos

- [x] Set up log controller on the rest server to receive incoming messaging from the UI
- [x] Define possible failure cases for Metamask transactions 
- [x] Define possible failure cases for IBC transfer transactions 
- [x] Log those occurrences to the rest-server so they show up in datadog

## Steps to Test
 
# Expected Behaviour

## Other Notes
